http://localhost:8080
#https://somind.tech
#https://somind.org

Content-Type: application/json; charset=utf-8

--

--
GET /dtlab-alligator/actor/machinery/one

--
GET /dtlab-alligator/actor/badmachine/one/badmodule/2

--
GET /dtlab-alligator/actor/machine/one/module/2/submodule/three

--
POST /dtlab-alligator/actor/badmachine/one/badmodule/2/
{
  "idx": 0,
  "value": 2.1,
  "datetime": "2020-09-13T15:31:21.671Z"
}

--
POST /dtlab-alligator/actor/machinery/one
{
  "idx": 0,
  "value": 5.5
}

--
GET /fitness

--
GET /observe

