http://localhost:8081

Content-Type: application/json; charset=utf-8
--

--
GET /dtlab-alligator/type/machinery

--
GET /dtlab-alligator/actor/machinery/one

--
GET /dtlab-alligator/actor/machinery/one/named

--
GET /dtlab-alligator/actor/machinery/one/pathed

--
POST /dtlab-alligator/actor/machinery/one
{
  "idx": 0,
  "value": 5.5
}

--
POST /dtlab-alligator/actor/machinery/one/pathed
{
  "name": "machinery.one.height",
  "value": 6.5
}

--
POST /dtlab-alligator/actor/machinery/one/named
{
  "name": "height",
  "value": 7.5
}

--
GET /fitness

--
GET /observe

