http://localhost:8081

Content-Type: application/json; charset=utf-8
--

--
DELETE /dtlab-alligator/actor/orbiting_body/Earth

--
GET /dtlab-alligator/actor/orbiting_body/Earth

--
GET /dtlab-alligator/actor/orbiting_body/Earth/object/3799865

--
GET /dtlab-alligator/actor/orbiting_body/Earth/object/3799865/named

--
GET /dtlab-alligator/actor/orbiting_body/Earth/object/3799865/pathed

--
GET /dtlab-alligator/actor/orbiting_body/Earth/object/3827337

--
GET /dtlab-alligator/actor/orbiting_body/Earth/object/haha

--
GET /dtlab-alligator/actor/orbiting_body/Earth/object/2440012

--
GET /dtlab-alligator/actor/orbiting_body/Earth/object/3726710

--
GET /fitness

--
GET /observe

