http://localhost:8081

Content-Type: application/json; charset=utf-8
--

--
POST /dtlab-alligator/type/machinery
{
  "props": ["height"]
}

--
GET /dtlab-alligator/type/machinery

--
GET /dtlab-alligator/actor/machinery

--
GET /dtlab-alligator/actor/machinery/one

--
GET /dtlab-alligator/actor/machinery/one?limit=5

--
GET /dtlab-alligator/actor/machinery/one?format=named

--
GET /dtlab-alligator/actor/machinery/one?format=pathed

--
POST /dtlab-alligator/actor/machinery/one
{
  "idx": 0,
  "value": 5.6
}

--
POST /dtlab-alligator/actor/machinery/one?format=pathed
{
  "name": "machinery.one.height",
  "value": 6.5
}

--
POST /dtlab-alligator/actor/machinery/one?format=named
{
  "name": "height",
  "value": 7.5
}

--
GET /fitness

--
GET /observe

