http://localhost:8081

Content-Type: application/json; charset=utf-8
--

--
DELETE /dtlab-alligator/type/machinery
--
POST /dtlab-alligator/type/machinery
{
  "props": [
    "height", 
    "height_readings_count",
    "height_readings_max",
    "height_readings_min",
    "days_online",
    "hours_online",
    "minutes_online",
    "height_first_seen"
  ]
}

--
GET /dtlab-alligator/type/machinery

--
GET /dtlab-alligator/actor/machinery

--
GET /dtlab-alligator/actor/machinery/twonew
--
GET /dtlab-alligator/actor/machinery/two
--
GET /dtlab-alligator/actor/machinery/three
--
GET /dtlab-alligator/actor/machinery/three?format=named

--
DELETE /dtlab-alligator/actor/machinery/three/operator
--
GET /dtlab-alligator/actor/machinery/three/operator

--
POST /dtlab-alligator/actor/machinery/three/operator
{
  "name": "count_height_readings",
  "implementation": "count",
  "params": [10.1,20.2],
  "input": [0],
  "output": [1]
}

--
POST /dtlab-alligator/actor/machinery/three/operator
{
  "name": "max_height_readings",
  "implementation": "max",
  "input": [0],
  "output": [2]
}

--
POST /dtlab-alligator/actor/machinery/three/operator
{
  "name": "min_height_readings",
  "implementation": "Min",
  "input": [0],
  "output": [3]
}

--
POST /dtlab-alligator/actor/machinery/three/operator
{
  "name": "days_online",
  "implementation": "days_active",
  "input": [0],
  "output": [4, 7]
}

--
POST /dtlab-alligator/actor/machinery/three/operator
{
  "name": "hours_online",
  "implementation": "hours_active",
  "input": [0],
  "output": [5, 7]
}

--
POST /dtlab-alligator/actor/machinery/three/operator
{
  "name": "minutes_online",
  "implementation": "minutes_active",
  "input": [0],
  "output": [6, 7]
}

--
GET /dtlab-alligator/actor/machinery/three?limit=10

--
GET /dtlab-alligator/actor/machinery/three?limit=3&offset=3

--
GET /dtlab-alligator/actor/machinery/three?limit=5&format=named

--
GET /dtlab-alligator/actor/machinery/three?limit=2&format=pathed

--
GET /dtlab-alligator/actor/machinery/three?format=named

--
GET /dtlab-alligator/actor/machinery/three?format=pathed

--
GET /dtlab-alligator/actor/machinery/three
--
POST /dtlab-alligator/actor/machinery/three
{
  "idx": 0,
  "value": 123.45
}

--
POST /dtlab-alligator/actor/machinery/won
{
  "idx": 0,
  "value": 9.17
}

--
POST /dtlab-alligator/actor/machinery/one?format=pathed
{
  "name": "machinery.three.height",
  "value": 6.5
}

--
POST /dtlab-alligator/actor/machinery/three3?format=named
{
  "name": "height",
  "value": 877.6
}

--
# WEBHOOK
GET /dtlab-alligator/webhook/fleetmgr-ss
--
DELETE /dtlab-alligator/webhook/fleetmgr-ss
--
POST /dtlab-alligator/webhook/fleetmgr-ss
{
  "target": {
    "host": "localhost",
    "port": 8082,
    "path": "/dtlab-alligator/ingest/telemetry/fleetmgr-ss",
    "tls": false
  },
  "dtType": "*",
  "eventType": "StateChange"
}
--
GET /dtlab-alligator/webhook/fleetmgr-cr
--
DELETE /dtlab-alligator/webhook/fleetmgr-cr
--
POST /dtlab-alligator/webhook/fleetmgr-cr
{
  "target": {
    "host": "localhost",
    "port": 8082,
    "path": "/dtlab-alligator/ingest/telemetry/fleetmgr-cr",
    "tls": false
  },
  "dtType": "*",
  "eventType": "Creation"
}



--
GET /fitness

--
GET /observe

