http://localhost:8081

Content-Type: application/json; charset=utf-8
--

--
DELETE /dtlab-alligator/type/machinery
--
POST /dtlab-alligator/type/machinery
{
  "props": ["height", "height_readings_count"]
}

--
GET /dtlab-alligator/type/machinery

--
GET /dtlab-alligator/actor/machinery

--
GET /dtlab-alligator/actor/machinery/two
--
GET /dtlab-alligator/actor/machinery/one
--
GET /dtlab-alligator/actor/machinery/one?format=named

--
DELETE /dtlab-alligator/actor/machinery/one/operator
--
GET /dtlab-alligator/actor/machinery/one/operator

--
POST /dtlab-alligator/actor/machinery/one/operator
{
  "name": "count_height_readings",
  "implementation": "count",
  "params": [10.1,20.2],
  "input": [0],
  "output": [1]
}

--
GET /dtlab-alligator/actor/machinery/one?limit=10

--
GET /dtlab-alligator/actor/machinery/one?limit=3&offset=3

--
GET /dtlab-alligator/actor/machinery/one?limit=5&format=named

--
GET /dtlab-alligator/actor/machinery/one?limit=2&format=pathed

--
GET /dtlab-alligator/actor/machinery/one?format=named

--
GET /dtlab-alligator/actor/machinery/one?format=pathed

--
POST /dtlab-alligator/actor/machinery/one
{
  "idx": 0,
  "value": 9.193
}

--
POST /dtlab-alligator/actor/machinery/two
{
  "idx": 0,
  "value": 9.17
}

--
POST /dtlab-alligator/actor/machinery/one?format=pathed
{
  "name": "machinery.one.height",
  "value": 6.5
}

--
POST /dtlab-alligator/actor/machinery/one?format=named
{
  "name": "height",
  "value": 7.5
}

--
GET /fitness

--
GET /observe

