http://localhost:8081
#https://somind.tech
#https://somind.org

Content-Type: application/json; charset=utf-8

--

--
GET /dtlab-alligator/type/orbiting_body

--
GET /dtlab-alligator/type/object

--
DELETE /dtlab-alligator/type/object

--
POST /dtlab-alligator/type/object
{
  "props": ["absolute_magnitude", "diameter_min", "diameter_max"]
}

--
POST /dtlab-alligator/type/orbiting_body
{
  "children": ["object"]
}

--
POST /dtlab-alligator/type/machinery
{
  "props": ["height"]
}

--
GET /fitness

--
GET /observe

