#http://localhost:8080
#https://somind.tech
https://somind.org

-ks

Content-Type: application/json; charset=utf-8

--

--
GET /dtlab-alligator/type/myType

--
POST /dtlab-alligator/type/myType

["four", "five", "six"]

--
GET /fitness

--
GET /observe

